const API_BASE="https://fieldnote-chat.nanotechnology728.workers.dev";
const STORAGE_KEY="fieldnote.conversationId";
const messagesEl=document.querySelector("#messages"),inputEl=document.querySelector("#message-input"),composer=document.querySelector("#composer"),sendButton=document.querySelector("#send-button"),newChatButton=document.querySelector("#new-chat"),documentInput=document.querySelector("#document-input"),documentStatus=document.querySelector("#document-status"),conversationList=document.querySelector("#conversation-list");
let conversationId=localStorage.getItem(STORAGE_KEY),busy=false;
const escapeHtml=value=>{const d=document.createElement("div");d.textContent=value;return d.innerHTML};
const renderAssistantText=text=>escapeHtml(text).replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>");
const scroll=()=>{messagesEl.scrollTop=messagesEl.scrollHeight};
function addUserMessage(text){document.querySelector("#empty-state")?.remove();const row=document.createElement("div"),bubble=document.createElement("div");row.className="message user";bubble.className="user-bubble";bubble.textContent=text;row.appendChild(bubble);messagesEl.appendChild(row);scroll()}
function addAssistantMessage(){document.querySelector("#empty-state")?.remove();const row=document.createElement("div"),content=document.createElement("div");row.className="message assistant";content.className="assistant-content";content.innerHTML='<span class="typing">Thinking…</span>';row.appendChild(content);messagesEl.appendChild(row);scroll();return{row,content}}
function resetView(){messagesEl.innerHTML='<div id="empty-state" class="empty-state"><span class="eyebrow">RESEARCH MODE</span><h2>Ask a question. Bring a document.</h2><p>Fieldnote can reason over your conversation and retrieve relevant passages from documents you add.</p></div>'}
async function createConversation(title="New conversation"){const r=await fetch(API_BASE+"/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:title.slice(0,80)})});if(!r.ok)throw new Error("Could not create conversation.");const d=await r.json();conversationId=d.id;localStorage.setItem(STORAGE_KEY,conversationId);await loadConversations()}
async function loadConversations(){try{const r=await fetch(API_BASE+"/conversations");if(!r.ok)return;const d=await r.json();conversationList.innerHTML="";for(const item of d.conversations||[]){const b=document.createElement("button");b.className="conversation-item"+(item.id===conversationId?" active":"");b.innerHTML='<span class="conversation-title"></span><span class="conversation-date"></span>';b.querySelector(".conversation-title").textContent=item.title||"Untitled";b.querySelector(".conversation-date").textContent=new Date(item.updated_at).toLocaleDateString();b.onclick=()=>openConversation(item.id);conversationList.appendChild(b)}}catch{}}
async function openConversation(id){conversationId=id;localStorage.setItem(STORAGE_KEY,id);resetView();const r=await fetch(API_BASE+"/conversations/"+encodeURIComponent(id));if(!r.ok)return;const d=await r.json();for(const m of d.messages||[]){if(m.role==="user")addUserMessage(m.content);else{const {content}=addAssistantMessage();content.innerHTML=renderAssistantText(m.content)}}await loadConversations()}
function renderCitations(content,citations=[]){if(!citations.length)return;const wrap=document.createElement("div");wrap.className="citations";for(const c of citations){const item=document.createElement("span");item.className="citation";item.textContent=c.title+(c.score?" · "+Math.round(c.score*100)+"%":"");wrap.appendChild(item)}content.appendChild(wrap)}
async function streamChat(text){if(!conversationId)await createConversation(text);const {row,content}=addAssistantMessage();let accumulated="";const r=await fetch(API_BASE+"/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversation_id:conversationId,message:text})});if(!r.ok){const e=await r.json().catch(()=>({}));row.remove();throw new Error(e?.error?.message||"Chat request failed.")}const reader=r.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line.startsWith("data: "))continue;const payload=line.slice(6);if(payload==="[DONE]")continue;let event;try{event=JSON.parse(payload)}catch{continue}if(event.type==="delta"){accumulated+=event.text;content.innerHTML=renderAssistantText(accumulated);scroll()}if(event.type==="citations")renderCitations(content,event.citations)}}if(!accumulated)content.textContent="No response returned."}
composer.onsubmit=async e=>{e.preventDefault();const text=inputEl.value.trim();if(!text||busy)return;busy=true;sendButton.disabled=true;inputEl.value="";inputEl.style.height="auto";addUserMessage(text);try{await streamChat(text);await loadConversations()}catch(err){const row=document.createElement("div");row.className="message assistant";row.innerHTML='<div class="error"></div>';row.querySelector(".error").textContent=err.message;messagesEl.appendChild(row)}finally{busy=false;sendButton.disabled=false;inputEl.focus()}};
inputEl.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();composer.requestSubmit()}};inputEl.oninput=()=>{inputEl.style.height="auto";inputEl.style.height=Math.min(inputEl.scrollHeight,140)+"px"};
newChatButton.onclick=async()=>{conversationId=null;localStorage.removeItem(STORAGE_KEY);resetView();await loadConversations();inputEl.focus()};
document.querySelectorAll("[data-prompt]").forEach(b=>b.onclick=()=>{inputEl.value=b.dataset.prompt;inputEl.focus()});
documentInput.onchange=async()=>{const file=documentInput.files?.[0];if(!file)return;documentStatus.textContent="Indexing…";try{if(!conversationId)await createConversation(file.name);let text;if(file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")){const pdfjs=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs");const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),c=await page.getTextContent();pages.push(c.items.map(x=>x.str).join(" "))}text=pages.join("\n\n")}else text=await file.text();if(text.length>100000)throw new Error("Document is too large. Keep it under 100,000 characters.");const r=await fetch(API_BASE+"/documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversation_id:conversationId,title:file.name,text})});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e?.error?.message||"Document indexing failed.")}documentStatus.textContent="Indexed"}catch(err){documentStatus.textContent="Index failed";alert(err.message)}finally{documentInput.value=""}};
loadConversations();
